name: publishNetlify
on: [push]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - run : sudo apt-get --assume-yes install asciidoctor 
    - run : make all
    - uses: actions/checkout@master
    - name: Publish
      uses : netlify/actions/cli@master
      with:
        args: deploy --prod --dir=./test/ --functions=functions
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}