name: bonjour
on: [push]


jobs:
  dire_bonjour:
    runs-on: ubuntu-20.04
    steps:
    - run: echo "Bonjour !"
    - run: ls -l
    - uses: actions/checkout@v2
    - run: netlify deploy --prod --dir=./dist/
